spring.application.name=grupo10
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/cancheros
spring.datasource.username=postgres
spring.datasource.password=ksotopro
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.data.mongodb.uri=mongodb+srv://cancherosgen_db_user:6uCSkBijaTeN7Z4D@cluster0.tpstpkm.mongodb.net/?appName=Cluster0