# =========================
# PostgreSQL
# =========================
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/cancheros
spring.datasource.username=postgres
spring.datasource.password=0000
spring.datasource.driver-class-name=org.postgresql.Driver

# Spring
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========================
# MongoDB Atlas
# =========================
#spring.mongodb.uri=mongodb+srv://cancherosgen_db_user:6uCSkBijaTeN7Z4D@cluster0.tpstpkm.mongodb.net/?appName=Cluster0

